using System.Text.RegularExpressions;
using AustralCreditAnalytics.Api.Models.Dfp;

namespace AustralCreditAnalytics.Api.Services;

/// <summary>
/// Catalogo dos modelos FRE (Formulario de Referencia / CVM) suportados pela importacao.
/// Cada modelo corresponde 1:1 a um arquivo "fre_cia_aberta_&lt;modelo&gt;_AAAA.csv" e a uma
/// tabela no schema [fre]. Gerado a partir dos metadados nativos da CVM (nomes/tipos das
/// colunas). Espelha o papel de <see cref="DfpDemonstracaoRegistry"/> para a base FRE.
/// Nenhum modelo FRE tem GRUPO_DFP, portanto todos sao TemConjunto:false.
/// </summary>
public static class FreModeloRegistry
{
    private static DfpColumn C(string name, DfpColumnKind kind) => new(name, kind);

    private static readonly IReadOnlyList<DfpDemonstracao> Todas = new List<DfpDemonstracao>
    {
        new("DOCUMENTO", "fre.Documento", "Indice de documentos FRE entregues", new[]
        {
            C("CATEG_DOC", DfpColumnKind.Text),
            C("CD_CVM", DfpColumnKind.Text),
            C("CNPJ_CIA", DfpColumnKind.Text),
            C("DENOM_CIA", DfpColumnKind.Text),
            C("DT_RECEB", DfpColumnKind.Date),
            C("DT_REFER", DfpColumnKind.Date),
            C("ID_DOC", DfpColumnKind.Int),
            C("LINK_DOC", DfpColumnKind.Text),
            C("VERSAO", DfpColumnKind.Short),
        }, TemConjunto: false),
        new("capital_social", "fre.CapitalSocial", "Capital Social", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Data_Autorizacao_Aprovacao", DfpColumnKind.Date),
            C("Prazo_Integralizacao", DfpColumnKind.Text),
            C("Valor_Capital", DfpColumnKind.Decimal),
            C("Quantidade_Acoes_Ordinarias", DfpColumnKind.Decimal),
            C("Quantidade_Acoes_Preferenciais", DfpColumnKind.Decimal),
            C("ID_Capital_Social", DfpColumnKind.Int),
            C("Tipo_Capital", DfpColumnKind.Text),
            C("Quantidade_Total_Acoes", DfpColumnKind.Decimal),
        }, TemConjunto: false),
        new("capital_social_aumento", "fre.CapitalSocialAumento", "Capital Social Aumento", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Emissao", DfpColumnKind.Date),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Fator_Cotacao", DfpColumnKind.Text),
            C("Criterio_Determinacao_Preco_Emissao", DfpColumnKind.Text),
            C("Preco_Emissao", DfpColumnKind.Decimal),
            C("Subscricao_Capital_Anterior", DfpColumnKind.Decimal),
            C("Valor_Total_Emissao", DfpColumnKind.Decimal),
            C("Quantidade_Acoes_Ordinarias", DfpColumnKind.Decimal),
            C("Quantidade_Acoes_Preferenciais", DfpColumnKind.Decimal),
            C("Orgao_Deliberacao_Aumento", DfpColumnKind.Text),
            C("Tipo_Subscricao", DfpColumnKind.Text),
            C("Data_Deliberacao", DfpColumnKind.Date),
            C("Forma_Integralizacao", DfpColumnKind.Text),
            C("ID_Capital_Social_Aumento", DfpColumnKind.Int),
            C("Quantidade_Total_Acoes", DfpColumnKind.Decimal),
        }, TemConjunto: false),
        new("capital_social_aumento_classe_acao", "fre.CapitalSocialAumentoClasseAcao", "Capital Social Aumento Classe Acao", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Tipo_Classe_Acao_Preferencial", DfpColumnKind.Text),
            C("Quantidade_Acoes", DfpColumnKind.Decimal),
            C("ID_Capital_Social_Aumento", DfpColumnKind.Int),
        }, TemConjunto: false),
        new("capital_social_classe_acao", "fre.CapitalSocialClasseAcao", "Capital Social Classe Acao", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("ID_Capital_Social", DfpColumnKind.Int),
            C("Tipo_Classe_Acao_Preferencial", DfpColumnKind.Text),
            C("Quantidade_Acoes", DfpColumnKind.Decimal),
        }, TemConjunto: false),
        new("capital_social_desdobramento", "fre.CapitalSocialDesdobramento", "Capital Social Desdobramento", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("ID_Capital_Social_Desdobramento", DfpColumnKind.Int),
            C("Data_Aprovacao", DfpColumnKind.Date),
            C("Quantidade_Total_Acoes_Antes_Aprovacao", DfpColumnKind.Decimal),
            C("Quantidade_Acoes_Preferenciais_Depois_Aprovacao", DfpColumnKind.Decimal),
            C("Quantidade_Acoes_Preferenciais_Antes_Aprovacao", DfpColumnKind.Decimal),
            C("Tipo_Evento", DfpColumnKind.Text),
            C("Quantidade_Total_Acoes_Depois_Aprovacao", DfpColumnKind.Decimal),
            C("Quantidade_Acoes_Ordinarias_Depois_Aprovacao", DfpColumnKind.Decimal),
            C("Quantidade_Acoes_Ordinarias_Antes_Aprovacao", DfpColumnKind.Decimal),
        }, TemConjunto: false),
        new("capital_social_desdobramento_classe_acao", "fre.CapitalSocialDesdobramentoClasseAcao", "Capital Social Desdobramento Classe Acao", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("ID_Capital_Social_Desdobramento", DfpColumnKind.Int),
            C("Quantidade_Acoes_Depois_Aprovacao", DfpColumnKind.Decimal),
            C("Quantidade_Acoes_Antes_Aprovacao", DfpColumnKind.Decimal),
            C("Tipo_Classe_Acao_Preferencial", DfpColumnKind.Text),
        }, TemConjunto: false),
        new("capital_social_reducao", "fre.CapitalSocialReducao", "Capital Social Reducao", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Quantidade_Acoes_Ordinarias", DfpColumnKind.Decimal),
            C("Reducao_Capital_Anterior", DfpColumnKind.Decimal),
            C("Quantidade_Acoes_Preferenciais", DfpColumnKind.Decimal),
            C("ID_Capital_Social_Reducao", DfpColumnKind.Int),
            C("Razao_Reducao", DfpColumnKind.Text),
            C("Forma_Restituicao", DfpColumnKind.Text),
            C("Data_Deliberacao", DfpColumnKind.Date),
            C("Data_Reducao", DfpColumnKind.Date),
            C("Valor_Total_Reducao", DfpColumnKind.Decimal),
            C("Valor_Restituido_Por_Acao", DfpColumnKind.Decimal),
            C("Quantidade_Total_Acoes", DfpColumnKind.Decimal),
        }, TemConjunto: false),
        new("capital_social_reducao_classe_acao", "fre.CapitalSocialReducaoClasseAcao", "Capital Social Reducao Classe Acao", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Tipo_Classe_Acao_Preferencial", DfpColumnKind.Text),
            C("Quantidade_Acoes", DfpColumnKind.Decimal),
            C("ID_Capital_Social_Reducao", DfpColumnKind.Int),
        }, TemConjunto: false),
        new("capital_social_titulo_conversivel", "fre.CapitalSocialTituloConversivel", "Capital Social Titulo Conversivel", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Condicoes_Conversao", DfpColumnKind.Text),
            C("ID_Capital_Social", DfpColumnKind.Int),
            C("Titulo_Conversivel_Acao", DfpColumnKind.Text),
        }, TemConjunto: false),
        new("direito_acao", "fre.DireitoAcao", "Direito Acao", new[]
        {
            C("Classe_Acao_Preferencial", DfpColumnKind.Text),
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Condicao_Alteracao_Direitos", DfpColumnKind.Text),
            C("Direito_Voto", DfpColumnKind.Text),
            C("Especie_Acao", DfpColumnKind.Text),
            C("Descricao_Voto_Restrito", DfpColumnKind.Text),
            C("Descricao_Restricao_Circulacao", DfpColumnKind.Text),
            C("Condicao_Conversibilidade_Efeito_Capital_Social", DfpColumnKind.Text),
            C("Resgatavel", DfpColumnKind.Text),
            C("Caracteristicas_Reembolso_Capital", DfpColumnKind.Text),
            C("Percentual_Tag_Along", DfpColumnKind.Decimal),
            C("Conversibilidade", DfpColumnKind.Text),
            C("Restricao_Circulacao", DfpColumnKind.Text),
            C("Direito_Dividendo", DfpColumnKind.Text),
            C("Direito_Reembolso_Capital", DfpColumnKind.Text),
            C("Hipotese_Resgate_Formula_Calculo", DfpColumnKind.Text),
            C("Outras_Caracteristicas_Relevantes", DfpColumnKind.Text),
        }, TemConjunto: false),
        new("distribuicao_capital", "fre.DistribuicaoCapital", "Distribuicao Capital", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("Data_Ultima_Assembleia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Percentual_Acoes_Ordinarias_Circulacao", DfpColumnKind.Decimal),
            C("Percentual_Acoes_Preferenciais_Circulacao", DfpColumnKind.Decimal),
            C("Percentual_Total_Acoes_Circulacao", DfpColumnKind.Decimal),
            C("Quantidade_Acionistas_Investidores_Institucionais", DfpColumnKind.Decimal),
            C("Quantidade_Acionistas_PF", DfpColumnKind.Decimal),
            C("Quantidade_Acionistas_PJ", DfpColumnKind.Decimal),
            C("Quantidade_Acoes_Ordinarias_Circulacao", DfpColumnKind.Decimal),
            C("Quantidade_Acoes_Preferenciais_Circulacao", DfpColumnKind.Decimal),
            C("Quantidade_Total_Acoes_Circulacao", DfpColumnKind.Decimal),
            C("Versao", DfpColumnKind.Short),
        }, TemConjunto: false),
        new("distribuicao_capital_classe_acao", "fre.DistribuicaoCapitalClasseAcao", "Distribuicao Capital Classe Acao", new[]
        {
            C("Classe_Acoes_Preferenciais", DfpColumnKind.Text),
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Percentual_Acoes_Preferenciais_Circulacao", DfpColumnKind.Decimal),
            C("Quantidade_Acoes_Preferenciais_Circulacao", DfpColumnKind.Decimal),
            C("Sigla_Classe_Acoes_Preferenciais", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
        }, TemConjunto: false),
        new("posicao_acionaria", "fre.PosicaoAcionaria", "Posicao Acionaria", new[]
        {
            C("Acionista", DfpColumnKind.Text),
            C("Acionista_Controlador", DfpColumnKind.Text),
            C("Acionista_Relacionado", DfpColumnKind.Text),
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("CPF_CNPJ_Acionista", DfpColumnKind.Text),
            C("CPF_CNPJ_Acionista_Relacionado", DfpColumnKind.Text),
            C("CPF_CNPJ_Representante_legal", DfpColumnKind.Text),
            C("Data_Composicao_Capital_Social", DfpColumnKind.Date),
            C("Data_Referencia", DfpColumnKind.Date),
            C("Data_Ultima_Alteracao", DfpColumnKind.Date),
            C("ID_Acionista", DfpColumnKind.Int),
            C("ID_Acionista_Relacionado", DfpColumnKind.Int),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nacionalidade", DfpColumnKind.Text),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Participante_Acordo_Acionistas", DfpColumnKind.Text),
            C("Percentual_Acao_Ordinaria_Circulacao", DfpColumnKind.Decimal),
            C("Percentual_Acao_Preferencial_Circulacao", DfpColumnKind.Decimal),
            C("Percentual_Total_Acoes_Circulacao", DfpColumnKind.Decimal),
            C("Quantidade_Acao_Ordinaria_Circulacao", DfpColumnKind.Decimal),
            C("Quantidade_Acao_Preferencial_Circulacao", DfpColumnKind.Decimal),
            C("Quantidade_Total_Acoes_Circulacao", DfpColumnKind.Decimal),
            C("Representante_Legal", DfpColumnKind.Text),
            C("Residente_Exterior", DfpColumnKind.Text),
            C("Sigla_UF", DfpColumnKind.Text),
            C("Tipo_Pessoa_Acionista", DfpColumnKind.Text),
            C("Tipo_Pessoa_Acionista_Relacionado", DfpColumnKind.Text),
            C("Tipo_Pessoa_Representante_Legal", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
        }, TemConjunto: false),
        new("posicao_acionaria_classe_acao", "fre.PosicaoAcionariaClasseAcao", "Posicao Acionaria Classe Acao", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Acionista", DfpColumnKind.Int),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Percentual_Acoes", DfpColumnKind.Decimal),
            C("Tipo_Classe_Acao_Preferencial", DfpColumnKind.Text),
            C("Quantidade_Acoes", DfpColumnKind.Decimal),
        }, TemConjunto: false),
        new("acao_entregue", "fre.AcaoEntregue", "Acao Entregue", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Fim_Exercicio_Social", DfpColumnKind.Date),
            C("Data_Inicio_Exercicio_Social", DfpColumnKind.Date),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Orgao_Administracao", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Valor_Diferenca_Aquisicao_Mercado", DfpColumnKind.Decimal),
            C("Preco_Medio_Ponderado_Aquisicao", DfpColumnKind.Decimal),
            C("Preco_Medio_Ponderado_Mercado", DfpColumnKind.Decimal),
            C("Quantidade_Acoes", DfpColumnKind.Int),
            C("Quantidade_Membros_Remunerados", DfpColumnKind.Decimal),
            C("Quantidade_Total_Membros", DfpColumnKind.Decimal),
        }, TemConjunto: false),
        new("mercado_estrangeiro", "fre.MercadoEstrangeiro", "Mercado Estrangeiro", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Emissao", DfpColumnKind.Date),
            C("Data_Inicio_Listagem", DfpColumnKind.Date),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Mercado", DfpColumnKind.Text),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Valor_Mobiliario", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Descricao_Instituicao_Custodiante", DfpColumnKind.Text),
            C("Descricao_Banco_Depositario", DfpColumnKind.Text),
            C("Percentual", DfpColumnKind.Decimal),
            C("Administradora", DfpColumnKind.Text),
            C("Pais_Negociacao", DfpColumnKind.Text),
            C("Descricao_Proporcao_Certificado", DfpColumnKind.Text),
            C("Identificacao_Valor_Mobiliario", DfpColumnKind.Text),
            C("Descricao_Segmento", DfpColumnKind.Text),
        }, TemConjunto: false),
        new("outro_valor_mobiliario", "fre.OutroValorMobiliario", "Outro Valor Mobiliario", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Emissao", DfpColumnKind.Date),
            C("Data_Referencia", DfpColumnKind.Date),
            C("Data_Vencimento", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Valor_Mobiliario", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Condicao_Alteracao_Direitos", DfpColumnKind.Text),
            C("Caracteristicas_Valores_Mobiliarios_Divida", DfpColumnKind.Text),
            C("Descricao_Restricao_Circulacao", DfpColumnKind.Text),
            C("Condicao_Conversibilidade_Efeito_Capital_Social", DfpColumnKind.Text),
            C("Resgatavel", DfpColumnKind.Text),
            C("Quantidade_Investidor_Institucional", DfpColumnKind.Decimal),
            C("Conversibilidade", DfpColumnKind.Text),
            C("Restricao_Circulacao", DfpColumnKind.Text),
            C("Valor", DfpColumnKind.Decimal),
            C("Saldo_Devedor", DfpColumnKind.Decimal),
            C("Quantidade_Pessoa_Fisica", DfpColumnKind.Decimal),
            C("Quantidade_Pessoa_Juridica", DfpColumnKind.Decimal),
            C("Quantidade", DfpColumnKind.Decimal),
            C("Hipotese_Resgate_Formula_Calculo", DfpColumnKind.Text),
            C("Identificacao_Valor_Mobiliario", DfpColumnKind.Text),
            C("Outras_Caracteristicas_Relevantes", DfpColumnKind.Text),
        }, TemConjunto: false),
        new("participacao_sociedade", "fre.ParticipacaoSociedade", "Participacao Sociedade", new[]
        {
            C("CNPJ", DfpColumnKind.Text),
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Codigo_CVM", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Data_Valor_Contabil", DfpColumnKind.Date),
            C("Data_Valor_Mercado", DfpColumnKind.Date),
            C("Valor_Mercado", DfpColumnKind.Decimal),
            C("Tipo_Sociedade", DfpColumnKind.Text),
            C("UF_Sede", DfpColumnKind.Text),
            C("Razao_Aquisicao_Manutencao", DfpColumnKind.Text),
            C("Valor_Contabil", DfpColumnKind.Decimal),
            C("Descricao_Atividades", DfpColumnKind.Text),
            C("Razao_Social", DfpColumnKind.Text),
            C("Participacao_Emissor", DfpColumnKind.Decimal),
            C("Possui_Registro_CVM", DfpColumnKind.Text),
            C("Municipio_Sede", DfpColumnKind.Text),
            C("Pais_Sede", DfpColumnKind.Text),
            C("ID_Sociedade", DfpColumnKind.Int),
        }, TemConjunto: false),
        new("participacao_sociedade_valorizacao_acao", "fre.ParticipacaoSociedadeValorizacaoAcao", "Participacao Sociedade Valorizacao Acao", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Data_Encerramento", DfpColumnKind.Date),
            C("Variacao_Percentual_Valor_Mercado", DfpColumnKind.Decimal),
            C("Variacao_Percentual_Valor_Contabil", DfpColumnKind.Decimal),
            C("Valor_Montante_Dividendos_Recebidos", DfpColumnKind.Decimal),
            C("ID_Sociedade", DfpColumnKind.Int),
        }, TemConjunto: false),
        new("plano_recompra", "fre.PlanoRecompra", "Plano Recompra", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Data_Fim_Recompra", DfpColumnKind.Date),
            C("Valor_Reserva_Disponivel_Recompra", DfpColumnKind.Decimal),
            C("Data_Deliberacao", DfpColumnKind.Date),
            C("ID_Plano_Recompra", DfpColumnKind.Int),
            C("Data_Inicio_Recompra", DfpColumnKind.Date),
            C("Outras_Caracteristicas_Importantes", DfpColumnKind.Text),
        }, TemConjunto: false),
        new("plano_recompra_classe_acao", "fre.PlanoRecompraClasseAcao", "Plano Recompra Classe Acao", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Quantidade_Prevista", DfpColumnKind.Long),
            C("Especie_Acao", DfpColumnKind.Text),
            C("Quantidade_Adquirida", DfpColumnKind.Long),
            C("Valor_Preco_Medio", DfpColumnKind.Decimal),
            C("Escala_Cotacao", DfpColumnKind.Text),
            C("Percentual_Previsto", DfpColumnKind.Decimal),
            C("Tipo_Classe_Acao_Preferencial", DfpColumnKind.Text),
            C("Percentual_Adquirido", DfpColumnKind.Decimal),
            C("ID_Plano_Recompra", DfpColumnKind.Int),
        }, TemConjunto: false),
        new("titular_valor_mobiliario", "fre.TitularValorMobiliario", "Titular Valor Mobiliario", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Valor_Mobiliario", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Quantidade_Investidor", DfpColumnKind.Decimal),
            C("Quantidade_Pessoa_Fisica", DfpColumnKind.Decimal),
            C("Quantidade_Pessoa_Juridica", DfpColumnKind.Decimal),
        }, TemConjunto: false),
        new("titulo_exterior", "fre.TituloExterior", "Titulo Exterior", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Emissao", DfpColumnKind.Date),
            C("Data_Referencia", DfpColumnKind.Date),
            C("Data_Vencimento", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Valor_Mobiliario", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Condicao_Alteracao_Direitos", DfpColumnKind.Text),
            C("Descricao_Restricao_Circulacao", DfpColumnKind.Text),
            C("Valor_Nominal", DfpColumnKind.Decimal),
            C("Possibilidade_Resgate", DfpColumnKind.Text),
            C("Conversibilidade", DfpColumnKind.Text),
            C("Restricao_Circulacao", DfpColumnKind.Text),
            C("Condicao_Conversibilidade", DfpColumnKind.Text),
            C("Saldo_Devedor", DfpColumnKind.Decimal),
            C("Quantidade", DfpColumnKind.Long),
            C("Outras_Caracteristicas", DfpColumnKind.Text),
            C("Identificacao_Valor_Mobiliario", DfpColumnKind.Text),
            C("Hipotese_Calculo_Resgate", DfpColumnKind.Text),
            C("Caracteristicas_Divida", DfpColumnKind.Text),
        }, TemConjunto: false),
        new("valor_mobiliario_tesouraria_movimentacao", "fre.ValorMobiliarioTesourariaMovimentacao", "Valor Mobiliario Tesouraria Movimentacao", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Fim_Exercicio_Social", DfpColumnKind.Date),
            C("Data_Inicio_Exercicio_Social", DfpColumnKind.Date),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Valor_Mobiliario", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Percentual_Relacao_Valores_Mobiliarios_Circulacao", DfpColumnKind.Decimal),
            C("Quantidade_Final", DfpColumnKind.Decimal),
            C("Valor_Total_Final", DfpColumnKind.Decimal),
            C("Valor_Total_Cancelado", DfpColumnKind.Decimal),
            C("Especie_Acao", DfpColumnKind.Text),
            C("Valor_Preco_Medio_Adquirido", DfpColumnKind.Decimal),
            C("Quantidade_Adquirida", DfpColumnKind.Decimal),
            C("Quantidade_Inicial", DfpColumnKind.Decimal),
            C("Escala_Cotacao", DfpColumnKind.Text),
            C("Valor_Preco_Medio_Final", DfpColumnKind.Decimal),
            C("Quantidade_Alienada", DfpColumnKind.Decimal),
            C("Valor_Total_Inicial", DfpColumnKind.Decimal),
            C("Descricao_Valor_Mobiliario", DfpColumnKind.Text),
            C("Tipo_Classe_Acao_Preferencial", DfpColumnKind.Text),
            C("Valor_Preco_Medio_Alienado", DfpColumnKind.Decimal),
            C("Valor_Preco_Medio_Inicial", DfpColumnKind.Decimal),
            C("Valor_Total_Alienado", DfpColumnKind.Decimal),
            C("Valor_Preco_Medio_Cancelado", DfpColumnKind.Decimal),
            C("Quantidade_Cancelada", DfpColumnKind.Decimal),
            C("Valor_Total_Adquirido", DfpColumnKind.Decimal),
        }, TemConjunto: false),
        new("valor_mobiliario_tesouraria_ultimo_exercicio", "fre.ValorMobiliarioTesourariaUltimoExercicio", "Valor Mobiliario Tesouraria Ultimo Exercicio", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Valor_Mobiliario", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Especie_Acao", DfpColumnKind.Text),
            C("Valor_Preco_Medio", DfpColumnKind.Decimal),
            C("Escala_Cotacao", DfpColumnKind.Text),
            C("Data_Aquisicao", DfpColumnKind.Date),
            C("Descricao_Valor_Mobiliario", DfpColumnKind.Text),
            C("Tipo_Classe_Acao_Preferencial", DfpColumnKind.Text),
            C("Percentual_Circulacao", DfpColumnKind.Decimal),
            C("Quantidade_Valor_Mobiliario", DfpColumnKind.Decimal),
        }, TemConjunto: false),
        new("volume_valor_mobiliario", "fre.VolumeValorMobiliario", "Volume Valor Mobiliario", new[]
        {
            C("Classe_Acao_Preferencial", DfpColumnKind.Text),
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Fim_Exercicio_Social", DfpColumnKind.Date),
            C("Data_Inicio_Exercicio_Social", DfpColumnKind.Date),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Valor_Mobiliario", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Valor_Maior_Cotacao", DfpColumnKind.Decimal),
            C("Especie_Acao", DfpColumnKind.Text),
            C("Valor_Volume_Negociado", DfpColumnKind.Decimal),
            C("Valor_Menor_Cotacao", DfpColumnKind.Decimal),
            C("Escala_Cotacao", DfpColumnKind.Text),
            C("Entidade_Administradora_Mercado", DfpColumnKind.Text),
            C("Mercado_Valor_Mobiliario", DfpColumnKind.Text),
            C("Valor_Cotacao_Media", DfpColumnKind.Decimal),
            C("Descricao_Outro_Valor_Mobiliario", DfpColumnKind.Text),
            C("Data_Fim_Trimestre", DfpColumnKind.Date),
        }, TemConjunto: false),
        new("remuneracao_acao", "fre.RemuneracaoAcao", "Remuneracao Acao", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Fim_Exercicio_Social", DfpColumnKind.Date),
            C("Data_Inicio_Exercicio_Social", DfpColumnKind.Date),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Orgao_Administracao", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Preco_Medio_Ponderado_Opcoes_Perdidas", DfpColumnKind.Decimal),
            C("Diluicao_Potencial", DfpColumnKind.Decimal),
            C("Quantidade_Membros_Remunerados", DfpColumnKind.Decimal),
            C("Preco_Medio_Ponderado_Opcoes_Exercidas", DfpColumnKind.Decimal),
            C("Preco_Medio_Ponderado_Opcoes_Em_Aberto", DfpColumnKind.Decimal),
            C("Quantidade_Total_Membros", DfpColumnKind.Decimal),
        }, TemConjunto: false),
        new("remuneracao_maxima_minima_media", "fre.RemuneracaoMaximaMinimaMedia", "Remuneracao Maxima Minima Media", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Fim_Exercicio_Social", DfpColumnKind.Date),
            C("Data_Inicio_Exercicio_Social", DfpColumnKind.Date),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Numero_Membros", DfpColumnKind.Decimal),
            C("Numero_Membros_Remunerados", DfpColumnKind.Decimal),
            C("Observacao", DfpColumnKind.Text),
            C("Orgao_Administracao", DfpColumnKind.Text),
            C("Valor_Maior_Remuneracao", DfpColumnKind.Decimal),
            C("Valor_Medio_Remuneracao", DfpColumnKind.Decimal),
            C("Valor_Menor_Remuneracao", DfpColumnKind.Decimal),
            C("Versao", DfpColumnKind.Short),
        }, TemConjunto: false),
        new("remuneracao_total_orgao", "fre.RemuneracaoTotalOrgao", "Remuneracao Total Orgao", new[]
        {
            C("Baseada_Acoes", DfpColumnKind.Decimal),
            C("Beneficios_Diretos_Indiretos", DfpColumnKind.Decimal),
            C("Bonus", DfpColumnKind.Decimal),
            C("Cessacao_Cargo", DfpColumnKind.Decimal),
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Comissoes", DfpColumnKind.Decimal),
            C("Data_Fim_Exercicio_Social", DfpColumnKind.Date),
            C("Data_Inicio_Exercicio_Social", DfpColumnKind.Date),
            C("Data_Referencia", DfpColumnKind.Date),
            C("Descricao_Outros_Remuneracoes_Fixas", DfpColumnKind.Text),
            C("Descricao_Outros_Remuneracoes_Variaveis", DfpColumnKind.Text),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Numero_Membros", DfpColumnKind.Decimal),
            C("Numero_Membros_Remunerados", DfpColumnKind.Decimal),
            C("Observacao", DfpColumnKind.Text),
            C("Orgao_Administracao", DfpColumnKind.Text),
            C("Outros_Valores_Fixos", DfpColumnKind.Decimal),
            C("Outros_Valores_Variaveis", DfpColumnKind.Decimal),
            C("Participacao_Resultados", DfpColumnKind.Decimal),
            C("Participacao_Reunioes", DfpColumnKind.Decimal),
            C("Participacoes_Comites", DfpColumnKind.Decimal),
            C("Pos_emprego", DfpColumnKind.Decimal),
            C("Salario", DfpColumnKind.Decimal),
            C("Total_Remuneracao", DfpColumnKind.Decimal),
            C("Total_Remuneracao_Orgao", DfpColumnKind.Decimal),
            C("Versao", DfpColumnKind.Short),
        }, TemConjunto: false),
        new("remuneracao_variavel", "fre.RemuneracaoVariavel", "Remuneracao Variavel", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Fim_Exercicio_Social", DfpColumnKind.Date),
            C("Data_Inicio_Exercicio_Social", DfpColumnKind.Date),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Orgao_Administracao", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Participacao_Valor_Efetivo", DfpColumnKind.Decimal),
            C("Bonus_Valor_Maximo", DfpColumnKind.Decimal),
            C("Bonus_Valor_Minimo", DfpColumnKind.Decimal),
            C("Participacao_Valor_Minimo", DfpColumnKind.Decimal),
            C("Quantidade_Membros_Remunerados", DfpColumnKind.Decimal),
            C("Bonus_Valor_Metas_Atingidas", DfpColumnKind.Decimal),
            C("Participacao_Valor_Metas_Atingidas", DfpColumnKind.Decimal),
            C("Participacao_Valor_Maximo", DfpColumnKind.Decimal),
            C("Bonus_Valor_Efetivo", DfpColumnKind.Decimal),
            C("Quantidade_Total_Membros", DfpColumnKind.Decimal),
        }, TemConjunto: false),
        new("administrador_declaracao_genero", "fre.AdministradorDeclaracaoGenero", "Administrador Declaracao Genero", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Orgao_Administracao", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Quantidade_Nao_Binario", DfpColumnKind.Int),
            C("Quantidade_Sem_Resposta", DfpColumnKind.Int),
            C("Quantidade_Feminino", DfpColumnKind.Int),
            C("Quantidade_Masculino", DfpColumnKind.Int),
            C("Quantidade_Outros", DfpColumnKind.Int),
            C("Nao_Aplicavel", DfpColumnKind.Text),
        }, TemConjunto: false),
        new("administrador_declaracao_raca", "fre.AdministradorDeclaracaoRaca", "Administrador Declaracao Raca", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Orgao_Administracao", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Quantidade_Preto", DfpColumnKind.Int),
            C("Quantidade_Indigena", DfpColumnKind.Int),
            C("Quantidade_Amarelo", DfpColumnKind.Int),
            C("Quantidade_Pardo", DfpColumnKind.Int),
            C("Quantidade_Sem_Resposta", DfpColumnKind.Int),
            C("Quantidade_Branco", DfpColumnKind.Int),
            C("Quantidade_Outros", DfpColumnKind.Int),
            C("Nao_Aplicavel", DfpColumnKind.Text),
        }, TemConjunto: false),
        new("administrador_membro_conselho_fiscal", "fre.AdministradorMembroConselhoFiscal", "Administrador Membro Conselho Fiscal", new[]
        {
            C("Cargo_Eletivo_Ocupado", DfpColumnKind.Text),
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Complemento_Cargo_Eletivo_Ocupado", DfpColumnKind.Text),
            C("CPF", DfpColumnKind.Text),
            C("Data_Eleicao", DfpColumnKind.Date),
            C("Data_Nascimento", DfpColumnKind.Date),
            C("Data_Posse", DfpColumnKind.Date),
            C("Data_Referencia", DfpColumnKind.Date),
            C("Eleito_Controlador", DfpColumnKind.Text),
            C("Experiencia_Profissional", DfpColumnKind.Text),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome", DfpColumnKind.Text),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Numero_Mandatos_Consecutivos", DfpColumnKind.Short),
            C("Orgao_Administracao", DfpColumnKind.Text),
            C("Outro_Cargo_Funcao", DfpColumnKind.Text),
            C("Percentual_Participacao_Reunioes", DfpColumnKind.Decimal),
            C("Prazo_Mandato", DfpColumnKind.Text),
            C("Profissao", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Data_Inicio_Primeiro_Mandato", DfpColumnKind.Date),
        }, TemConjunto: false),
        new("auditor", "fre.Auditor", "Auditor", new[]
        {
            C("Auditor", DfpColumnKind.Text),
            C("CNPJ_Auditor", DfpColumnKind.Text),
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Codigo_CVM_Auditor", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Justificativa_Substituicao", DfpColumnKind.Text),
            C("Servico_Contratado", DfpColumnKind.Text),
            C("Remuneracao_Auditor", DfpColumnKind.Text),
            C("Tipo_Origem_Auditor", DfpColumnKind.Text),
            C("CPF_Auditor", DfpColumnKind.Text),
            C("Data_Inicio_Prestacao_Servico", DfpColumnKind.Date),
            C("Data_Fim_Contratacao", DfpColumnKind.Date),
            C("Razao_Apresentada", DfpColumnKind.Text),
            C("ID_Auditor", DfpColumnKind.Int),
            C("Data_Inicio_Contratacao", DfpColumnKind.Date),
        }, TemConjunto: false),
        new("auditor_responsavel", "fre.AuditorResponsavel", "Auditor Responsavel", new[]
        {
            C("Bairro", DfpColumnKind.Text),
            C("CEP", DfpColumnKind.Text),
            C("Cidade", DfpColumnKind.Text),
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Complemento", DfpColumnKind.Text),
            C("CPF_Responsavel_Tecnico", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("DDD_Telefone", DfpColumnKind.Text),
            C("DDI_Telefone", DfpColumnKind.Text),
            C("Email", DfpColumnKind.Text),
            C("Fax", DfpColumnKind.Text),
            C("ID_Documento", DfpColumnKind.Int),
            C("Logradouro", DfpColumnKind.Text),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Pais", DfpColumnKind.Text),
            C("Responsavel_Tecnico", DfpColumnKind.Text),
            C("Sigla_UF", DfpColumnKind.Text),
            C("Telefone", DfpColumnKind.Text),
            C("UF", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Data_Inicio_Responsavel_Tecnico", DfpColumnKind.Date),
            C("Data_Fim_Responsavel_Tecnico", DfpColumnKind.Date),
            C("ID_Auditor", DfpColumnKind.Int),
        }, TemConjunto: false),
        new("membro_comite", "fre.MembroComite", "Membro Comite", new[]
        {
            C("Cargo_Ocupado", DfpColumnKind.Text),
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("CPF", DfpColumnKind.Text),
            C("Data_Eleicao", DfpColumnKind.Date),
            C("Data_Nascimento", DfpColumnKind.Date),
            C("Data_Posse", DfpColumnKind.Date),
            C("Data_Referencia", DfpColumnKind.Date),
            C("Descricao_Outro_Cargo_Ocupado", DfpColumnKind.Text),
            C("Descricao_Outros_Comites", DfpColumnKind.Text),
            C("Experiencia_Profissional", DfpColumnKind.Text),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome", DfpColumnKind.Text),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Numero_Mandatos_Consecutivos", DfpColumnKind.Short),
            C("Outro_Cargo_Funcao", DfpColumnKind.Text),
            C("Percentual_Participacao_Reunioes", DfpColumnKind.Decimal),
            C("Prazo_Mandato", DfpColumnKind.Text),
            C("Profissao", DfpColumnKind.Text),
            C("Tipo_Comite", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Data_Inicio_Primeiro_Mandato", DfpColumnKind.Date),
        }, TemConjunto: false),
        new("politica_negociacao", "fre.PoliticaNegociacao", "Politica Negociacao", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("ID_Politica", DfpColumnKind.Int),
            C("Data_Aprovacao", DfpColumnKind.Date),
            C("Vedacao_Procedimentos_Fiscalizacao", DfpColumnKind.Text),
            C("Principais_Caracteristicas", DfpColumnKind.Text),
            C("Orgao_Aprovacao", DfpColumnKind.Text),
        }, TemConjunto: false),
        new("politica_negociacao_cargo", "fre.PoliticaNegociacaoCargo", "Politica Negociacao Cargo", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("ID_Politica", DfpColumnKind.Int),
            C("Cargo_Pessoa_Vinculada", DfpColumnKind.Text),
        }, TemConjunto: false),
        new("relacao_familiar", "fre.RelacaoFamiliar", "Relacao Familiar", new[]
        {
            C("Cargo_Administrador", DfpColumnKind.Text),
            C("Cargo_Pessoa_Relacionada", DfpColumnKind.Text),
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("CNPJ_Emissor", DfpColumnKind.Text),
            C("CNPJ_Emissor_Pessoa_Relacionada", DfpColumnKind.Text),
            C("CPF_Administrador", DfpColumnKind.Text),
            C("CPF_Pessoa_Relacionada", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Administrador", DfpColumnKind.Text),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Nome_Emissor", DfpColumnKind.Text),
            C("Nome_Emissor_Pessoa_Relacionada", DfpColumnKind.Text),
            C("Nome_Pessoa_Relacionada", DfpColumnKind.Text),
            C("Observacao", DfpColumnKind.Text),
            C("Tipo_Parentesco", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
        }, TemConjunto: false),
        new("relacao_subordinacao", "fre.RelacaoSubordinacao", "Relacao Subordinacao", new[]
        {
            C("Cargo_Administrador", DfpColumnKind.Text),
            C("Cargo_Pessoa_Relacionada", DfpColumnKind.Text),
            C("Categoria_Pessoa_Relacionada", DfpColumnKind.Text),
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("CPF_Administrador", DfpColumnKind.Text),
            C("Data_Fim_Exercicio_Social", DfpColumnKind.Date),
            C("Data_Inicio_Exercicio_Social", DfpColumnKind.Date),
            C("Data_Referencia", DfpColumnKind.Date),
            C("Documento_Pessoa_Relacionada", DfpColumnKind.Text),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Administrador", DfpColumnKind.Text),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Nome_Pessoa_Relacionada", DfpColumnKind.Text),
            C("Observacao", DfpColumnKind.Text),
            C("Tipo_Pessoa_Relacionada", DfpColumnKind.Text),
            C("Tipo_Relacao", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
        }, TemConjunto: false),
        new("responsavel", "fre.Responsavel", "Responsavel", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Cargo_Responsavel", DfpColumnKind.Text),
            C("Nome_Responsavel", DfpColumnKind.Text),
        }, TemConjunto: false),
        new("ativo_imobilizado", "fre.AtivoImobilizado", "Ativo Imobilizado", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Pais", DfpColumnKind.Text),
            C("UF", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Descricao_Bem_Ativo", DfpColumnKind.Text),
            C("Tipo_Propriedade", DfpColumnKind.Text),
            C("Municipio", DfpColumnKind.Text),
        }, TemConjunto: false),
        new("ativo_intangivel", "fre.AtivoIntangivel", "Ativo Intangivel", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Tipo_Ativo", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Descricao_Ativo", DfpColumnKind.Text),
            C("Evento_Perda_Direito", DfpColumnKind.Text),
            C("Consequencia_Perda_Direito", DfpColumnKind.Text),
            C("Duracao", DfpColumnKind.Text),
        }, TemConjunto: false),
        new("empregado_declaracao_genero", "fre.EmpregadoDeclaracaoGenero", "Empregado Declaracao Genero", new[]
        {
            C("Classe", DfpColumnKind.Text),
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Versao", DfpColumnKind.Short),
            C("Quantidade_Nao_Binario", DfpColumnKind.Int),
            C("Quantidade_Sem_Resposta", DfpColumnKind.Int),
            C("Quantidade_Feminino", DfpColumnKind.Int),
            C("Quantidade_Masculino", DfpColumnKind.Int),
            C("Quantidade_Outros", DfpColumnKind.Int),
        }, TemConjunto: false),
        new("empregado_declaracao_raca", "fre.EmpregadoDeclaracaoRaca", "Empregado Declaracao Raca", new[]
        {
            C("Classe", DfpColumnKind.Text),
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Versao", DfpColumnKind.Short),
            C("Quantidade_Preto", DfpColumnKind.Int),
            C("Quantidade_Indigena", DfpColumnKind.Int),
            C("Quantidade_Amarelo", DfpColumnKind.Int),
            C("Quantidade_Pardo", DfpColumnKind.Int),
            C("Quantidade_Sem_Resposta", DfpColumnKind.Int),
            C("Quantidade_Branco", DfpColumnKind.Int),
            C("Quantidade_Outros", DfpColumnKind.Int),
        }, TemConjunto: false),
        new("empregado_local_faixa_etaria", "fre.EmpregadoLocalFaixaEtaria", "Empregado Local Faixa Etaria", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Local", DfpColumnKind.Text),
            C("Quantidade_Ate30Anos", DfpColumnKind.Int),
            C("Quantidade_Acima50Anos", DfpColumnKind.Int),
            C("Quantidade_30a50Anos", DfpColumnKind.Int),
        }, TemConjunto: false),
        new("grupo_economico_reestruturacao", "fre.GrupoEconomicoReestruturacao", "Grupo Economico Reestruturacao", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Data_Operacao", DfpColumnKind.Date),
            C("Descricao_Operacao", DfpColumnKind.Text),
            C("Evento_Societario", DfpColumnKind.Text),
        }, TemConjunto: false),
        new("historico_emissor", "fre.HistoricoEmissor", "Historico Emissor", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("ID_Documento", DfpColumnKind.Int),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
            C("Data_Registro_Emissor", DfpColumnKind.Date),
            C("Prazo_Duracao_Emissor", DfpColumnKind.Date),
            C("Requisicao_Registro_Emissor", DfpColumnKind.Text),
            C("Data_Constituicao_Emissor", DfpColumnKind.Date),
            C("Pais_Constituicao_Emissor", DfpColumnKind.Text),
            C("Sigla_Pais_Constituicao_Emissor", DfpColumnKind.Text),
            C("Forma_Constituicao_Emissor", DfpColumnKind.Text),
        }, TemConjunto: false),
        new("transacao_parte_relacionada", "fre.TransacaoParteRelacionada", "Transacao Parte Relacionada", new[]
        {
            C("CNPJ_Companhia", DfpColumnKind.Text),
            C("Data_Referencia", DfpColumnKind.Date),
            C("Data_Transacao", DfpColumnKind.Date),
            C("Documento_Parte_Relacionada", DfpColumnKind.Text),
            C("Duracao_Transacao", DfpColumnKind.Text),
            C("Emprestimo_Divida", DfpColumnKind.Text),
            C("Especificacao_Posicao_Contratual_Emissor", DfpColumnKind.Text),
            C("Garantia_Seguro", DfpColumnKind.Text),
            C("ID_Documento", DfpColumnKind.Int),
            C("Montante_Envolvido", DfpColumnKind.Decimal),
            C("Montante_Interesse_Parte_Relacionada", DfpColumnKind.Text),
            C("Natureza_Razao_Operacao", DfpColumnKind.Text),
            C("Nome_Companhia", DfpColumnKind.Text),
            C("Objeto_Contrato", DfpColumnKind.Text),
            C("Parte_Relacionada", DfpColumnKind.Text),
            C("Posicao_Contratual_Emissor", DfpColumnKind.Text),
            C("Relacao_Emissor", DfpColumnKind.Text),
            C("Rescisao", DfpColumnKind.Text),
            C("Saldo_Existente", DfpColumnKind.Text),
            C("Taxa_Juros", DfpColumnKind.Decimal),
            C("Tipo_Pessoa", DfpColumnKind.Text),
            C("Versao", DfpColumnKind.Short),
        }, TemConjunto: false),
    };

    private static readonly IReadOnlyDictionary<string, DfpDemonstracao> PorTipo =
        Todas.ToDictionary(d => d.Tipo, StringComparer.OrdinalIgnoreCase);

    /// <summary>Todos os modelos FRE suportados (inclui o indice DOCUMENTO).</summary>
    public static IReadOnlyList<DfpDemonstracao> Listar() => Todas;

    /// <summary>Resolve o modelo pela chave (case-insensitive). Null se desconhecido.</summary>
    public static DfpDemonstracao? Resolver(string? tipo)
        => tipo is not null && PorTipo.TryGetValue(tipo.Trim(), out var d) ? d : null;

    private const string Prefixo = "fre_cia_aberta";
    private static readonly Regex AnoSufixo = new(@"_(19|20)\d{2}$", RegexOptions.Compiled);
    private static readonly Regex AnoTotal  = new(@"^(19|20)\d{2}$", RegexOptions.Compiled);

    /// <summary>
    /// Identifica a chave do modelo a partir do nome do arquivo de dados
    /// "fre_cia_aberta_&lt;modelo&gt;_AAAA.csv". Remove o prefixo e o sufixo do ano; o restante
    /// e casado (exato, case-insensitive) contra o registry. Nome sem modelo (apenas o ano,
    /// ex.: "fre_cia_aberta_2024.csv") -> DOCUMENTO. Retorna null se nao reconhecido.
    /// </summary>
    public static string? IdentificarPorArquivo(string? nomeArquivo)
    {
        if (string.IsNullOrWhiteSpace(nomeArquivo))
            return null;

        var nome = Path.GetFileNameWithoutExtension(nomeArquivo).Trim().ToLowerInvariant();
        if (!nome.StartsWith(Prefixo, StringComparison.Ordinal))
            return null;

        var resto = nome.Substring(Prefixo.Length).Trim('_');
        var m = AnoSufixo.Match(resto);
        if (m.Success)
            resto = resto.Substring(0, m.Index);
        else if (AnoTotal.IsMatch(resto))
            resto = string.Empty;

        if (resto.Length == 0)
            return "DOCUMENTO";

        return PorTipo.TryGetValue(resto, out var d) ? d.Tipo : null;
    }
}
